# Generated by Django 3.0.2 on 2020-01-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
                ('apellido', models.CharField(max_length=400)),
                ('cedula', models.IntegerField(unique=True)),
                ('fechaNacimiento', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=800)),
            ],
        ),
    ]
