# Generated by Django 3.0.2 on 2020-03-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='fechaSuscricion',
            new_name='fechaSuscripcion',
        ),
    ]
