# Generated by Django 3.0.2 on 2020-03-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='tipoSuscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoriaID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tipoID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.tipoSuscripcion'),
            preserve_default=False,
        ),
    ]
