# Generated by Django 3.0.2 on 2020-03-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0002_auto_20200302_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='gerente',
            name='especialidadID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.especialidad'),
            preserve_default=False,
        ),
    ]
