# Generated by Django 3.0.2 on 2020-03-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0002_auto_20200229_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proovedor_Producto',
            new_name='proveedor_Producto',
        ),
    ]
