# Generated by Django 3.0.2 on 2020-02-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioUnidad',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=10),
        ),
    ]
