# Generated by Django 3.0.2 on 2020-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0003_auto_20200208_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioUnidad',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
