# Generated by Django 3.0.2 on 2020-03-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0003_auto_20200302_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleados_ventas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('empleadoNombre', models.CharField(max_length=400)),
                ('empleadoApellido', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'empleados_ventas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'especialidad', 'verbose_name_plural': 'especialidades'},
        ),
    ]
