# Generated by Django 3.0.2 on 2020-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0004_auto_20200208_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
                ('telefono', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fechaNacimiento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=12),
        ),
    ]
