# Generated by Django 3.0.2 on 2020-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0004_auto_20200302_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
