# Generated by Django 3.0.2 on 2020-02-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0005_auto_20200209_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Direccion',
        ),
        migrations.CreateModel(
            name='cliente_direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.ciudad')),
                ('clienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente')),
                ('municipioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.municipio')),
            ],
        ),
    ]
