# Generated by Django 3.0.2 on 2020-03-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0005_auto_20200303_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empleados_ventas',
        ),
        migrations.AlterField(
            model_name='precioproducto',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
