# Generated by Django 3.0.2 on 2020-03-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0006_auto_20200304_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioproducto',
            name='fecha',
            field=models.CharField(default='', max_length=12),
        ),
    ]
