# Generated by Django 3.0.2 on 2020-02-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0006_auto_20200209_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_direccion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.CreateModel(
            name='ciudad_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.ciudad')),
                ('proveedorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.proveedor')),
            ],
        ),
    ]
