# Generated by Django 3.0.2 on 2020-02-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0007_auto_20200209_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'ciudad', 'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterModelOptions(
            name='ciudad_proveedor',
            options={'verbose_name': 'ciudad_proveedor', 'verbose_name_plural': 'ciudad_proveedores'},
        ),
        migrations.AlterModelOptions(
            name='cliente_direccion',
            options={'verbose_name': 'cliente_direccion', 'verbose_name_plural': 'cliente_direcciones'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterField(
            model_name='cliente_direccion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVenta', models.DateTimeField(auto_now=True)),
                ('clienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente')),
            ],
        ),
    ]
