# Generated by Django 3.0.2 on 2020-02-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0008_auto_20200209_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_direccion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='informacion_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=4)),
                ('productoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto')),
                ('ventaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.venta')),
            ],
        ),
    ]
