# Generated by Django 3.0.2 on 2020-02-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0009_auto_20200209_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=400)),
                ('apellido', models.CharField(max_length=400)),
                ('cedula', models.IntegerField(unique=True)),
                ('telefono', models.CharField(default='', max_length=12)),
                ('fechaNacimiento', models.CharField(default='', max_length=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente_direccion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.AlterField(
            model_name='informacion_venta',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.CreateModel(
            name='proveedor_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto')),
                ('proveedorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.proveedor')),
            ],
        ),
    ]
