# Generated by Django 3.0.2 on 2020-02-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0010_auto_20200209_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_direccion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.AlterField(
            model_name='informacion_venta',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='proveedor_producto',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.CreateModel(
            name='vendedor_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.vendedor')),
                ('ventaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.venta')),
            ],
        ),
        migrations.CreateModel(
            name='categoria_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.categoria')),
                ('productoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto')),
            ],
        ),
    ]
