# Generated by Django 3.0.2 on 2020-02-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0011_auto_20200209_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_producto',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='cliente_direccion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.AlterField(
            model_name='informacion_venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informacion_venta',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='proveedor_producto',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
    ]
