# Generated by Django 3.0.2 on 2020-02-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_aplicacion', '0012_auto_20200209_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSuscricion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('clienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente')),
            ],
            options={
                'verbose_name': 'suscripcion',
                'verbose_name_plural': 'suscripciones',
            },
        ),
        migrations.CreateModel(
            name='tipoSuscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'tipoSuscripcion',
                'verbose_name_plural': 'tipoSuscripciones',
            },
        ),
        migrations.AlterField(
            model_name='categoria_producto',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='cliente_direccion',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.AlterField(
            model_name='informacion_venta',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='proveedor_producto',
            name='productoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='clienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.cliente'),
        ),
        migrations.CreateModel(
            name='tipo_Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscripcionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.suscripcion')),
                ('tipoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_aplicacion.tipoSuscripcion')),
            ],
            options={
                'verbose_name': 'tipo_suscripcion',
                'verbose_name_plural': 'tipo_suscripciones',
            },
        ),
    ]
